### ISSUE TITLE
Idea: Disjunction across facets

### ISSUE THREAD

**Issue by cldwalker** [metreeca/self#4]
**Is your feature request related to a problem or a specific use case?**

Yep. I'd like to be able to filter by an OR query that spans across two facets e.g. name = 'X' OR type = 'Y'

**Describe the solution you'd like**

Simplest would be a boolean option in the right sidebar that toggles AND/ORing of facets. Default to AND as that is the current behavior

**Describe alternatives you've considered**

You could make a more complex feature that allows a user to define facet groups and then let users define ANDing and ORing. You could also allow users to type such requests in the input bar but that may be complex to support

**Additional thoughts**

I noticed that typing in the filter box with multiple facets has an OR like effect but it's unclear how that works and wouldn't fit most use cases where users want to filter by 2 different values, not the same value across facets

Cheers

**Comment by knoan** [comment]
Not easily supported within the current architecture: disjunctive filtering would require extensive work on the SPARQL generation engine and a careful extension of the UI, in order to avoid exposing casual / non-tech users to advanced features (which is one of the major requirements of the project).

Will re-evaluate after metreeca/self query engine is eventually merged with [metreeca/link](https://github.com/metreeca/link) (which already supports disjunctive queries) and its UI is migrated to the [plannded](https://github.com/metreeca/tile) web component architecture (which will support full customisation).

**Comment by cldwalker** [comment]
Bummer to hear and thanks for communicating where there are limitations. Look forward to seeing what the tile project provides
